### ISSUE TITLE
sort dashboard recent payments list by date decending order

### ISSUE THREAD

**Issue by killarny** [invoiceninja/admin-portal#313]
**What version of Invoice Ninja are you running? ie v4.5 / v5**
v5.2.17-C56

**What environment are you running?**
Docker

**Have you checked log files (storage/logs/) Please provide redacted output**
N/A

**Have you searched existing issues?**
Yes, didn't notice any with this in the title.

**Have you reported this to Slack/forum before posting?**
No, it seems pretty clear cut to me, but I can post it there too if that's desirable.

**Describe the bug**
As shown in the attached screenshot, the recent payments list is not sorted by date. It is also failing to show payments more recent than the 30 Jun 2021 payment in the screenshot. This list should probably be sorted by date decending instead, which would presumably fix the "missing" payments too.

**Steps To Reproduce**
Create some payments with different dates, and observe that they are shown out of order on the recent payments list.

**Expected behavior**
Recent payments list should be sorted by date.

**Screenshots**
![image](https://user-images.githubusercontent.com/29001/129243023-cfa710e0-134a-40d5-90a2-7250c50ae5ef.png)

**Additional context**
N/A

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
Yes, it is happening there too.

**Comment by hillelcoren** [comment]
This should be corrected in the next release

**Comment by killarny** [comment]
Not sure if by next version you meant v5.2.18 or the next one after that (your comment was apparently the same day that v5.2.18 came out), but it's still happening in v5.2.18-C58 at least.

**Comment by hillelcoren** [comment]
It's possible it missed 5.2.18, please let us know if you see the problem in .19.
