### ISSUE TITLE
Email template selection drop down shown as blank

### ISSUE THREAD

**Issue by mrkylegp** [invoiceninja/admin-portal#471]
When sending emails sometimes (in this case for the third time), Invoice ninja shows that my third template is going to be sent but the drop down is blank. It's almost not possible to tell there is a selection box there (see photo).

Expected behavior is that it would show "Third Reminder" in the drop down corresponding to the template about to be sent.

This used to work normally but something changed in the last few updates and now it's possible for the drop down to become blank as you can see in the photo:

![Screenshot 2022-08-03 084052](https://user-images.githubusercontent.com/52687659/182486008-8aa23c6f-0b43-4da1-aa09-4fb5a2a2f5fa.png)

**Comment by hillelcoren** [comment]
Thanks for reporting this!

I think the app is trying to select the endless reminder option but it isn't in the list, we've corrected this.

**Comment by mrkylegp** [comment]
@hillelcoren Yes, this is what is happening. Just updated to v5.5.6 and this issue is still present?

**Comment by hillelcoren** [comment]
Is this still happening?

**Comment by mrkylegp** [comment]
> Is this still happening?

I haven't actually observed this issue for a while. I'll close for now. Thanks @hillelcoren
