### ISSUE TITLE
Profit Reports are Calculated Wrong (BUG?)

### ISSUE THREAD

**Issue by atb79** [invoiceninja/admin-portal#537]
Hi there, I’m a new user of the online platform, I have tried out the hosted version and liked it so bought the white label… then realized your online solution is quite nice and can be nicely integrated into my website as a customer area. Overall I’m quite happy so far with the solution, just need some help as I seem to have found a bug with your profit/loss reports for QUOTES.

Below, screenshot of the v5 application Checking by LINE the profit is just wrong. Below export to excel to see what it “should be” - HUGE difference in the profit.
![image](https://user-images.githubusercontent.com/122029864/210793323-4996a4ab-8272-4b22-b34d-6e13f3d94be1.png)
We use this quite extensively to check and approve our quotes internally before we send them out to clients and need a reliable way of checking overall profit.

It would be really great to have a % of profit on the totals - save a LOT of time. We have firm policies or agreements with clients governing how much profit we can make and again this would be very helpful to us.

**Comment by hillelcoren** [comment]
We've fixed the bug and added a 'Markup' column to the invoice/quote item reports, thanks for the suggestion!

**Comment by atb79** [comment]
This is fantastic, how do i use it ? I've cleared cache and tried to login again but it is still the same.
Sorry for the noob questions...

**Comment by hillelcoren** [comment]
The change will be included with the next release
